apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadata.labels.app }}-deployment
  labels:
    app: {{ .Values.metadata.labels.app }}
    environment: {{ .Values.metadata.labels.environment }}
    tier: {{ .Values.metadata.labels.tier }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.metadata.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.metadata.labels.app }}
        environment: {{ .Values.metadata.labels.environment }}
        tier: {{ .Values.metadata.labels.tier }}
    spec:
      containers:
        - image: {{ .Values.containers.image }}/{{ .Values.metadata.labels.app }}:latest
          name: {{ .Values.metadata.labels.app }}-container
          env:
            - name: PORT
              value: "{{ .Values.containers.ports.containerPort }}"
          ports:
            - containerPort: {{ .Values.containers.ports.containerPort }}
              protocol: TCP
          livenessProbe:
            grpc:
              port: {{ .Values.containers.ports.containerPort }}
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            grpc:
              port: {{ .Values.containers.ports.containerPort }}
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          resources:
            requests:
              memory: "180Mi"
              cpu: "200m"
            limits:
              memory: "300Mi"
              cpu: "300m"