apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.metadata.labels.app }}-service
  labels:
    app: {{ .Values.metadata.labels.app }}
spec:
  selector:
    app: {{ .Values.metadata.labels.app }}
  ports:
    - protocol: TCP
      port: {{ .Values.containers.ports.containerPort }}
  type: ClusterIP